# version: '5.0.0' this is redundant for modern versions
services:
  zookeeper:
    # using a pre-built Docker image for Zookeeper from Confluent Inc.
    image: confluentinc/cp-zookeeper:7.3.0

    hostname: zookeeper

    container_name: zookeeper
    # Map port 2181 on the host machine to port 2181 in the container.
    ports:
      - "2181:2181"
    # Environment variables to configure Zookeeper.
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000


  kafka:
    # using a pre-built Docker image for Kafka
    image: confluentinc/cp-kafka:7.3.0
    hostname: kafka
    container_name: kafka
    
    depends_on:
      - zookeeper
    # Map port 9092 on the host machine to port 9092 in the container.
    ports:
      - "9092:9092"
    # Environment variables to configure Kafka.
    environment:
      # The unique ID for this broker in the Kafka cluster.
      KAFKA_BROKER_ID: 1
      # The address of the Zookeeper service. Note we use the service name 'zookeeper'.
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  python-app:

    build: .
    hostname: python-app
    container_name: python-app

    depends_on:
      - kafka

    volumes:
      - .:/app

    working_dir: /app

    command: tail -f /dev/null
